sudo: required

language: node_js

services:
  - docker

node_js:
 - 8

before_install:
 - yarn

script: yarn build

after_success:
  - docker login -u _ -p "$HEROKU_TOKEN" registry.heroku.com
  - docker build -t registry.heroku.com/vivalavinyl/web .
  - docker push registry.heroku.com/vivalavinyl/web 
  - heroku container:release web -a vivalavinyl
