version: '3.1'
services:
  web:
    build: .
    image: darthhater/bored-board-webapp:latest
    ports:
      - '8080:8080'
    command: yarn start
  # backend:
  #   image: darthhater/bored-board-service:latest
  #   container_name: backend
  #   ports:
  #     - '8000:8000'
