export const threadConstants = {
    ADD_POST: 'ADD_POST',
    EDIT_POST: 'EDIT_POST',
    ADD_THREAD: 'ADD_THREAD',
    RECIEVE_POST: 'RECIEVE_POST',
    DELETE_THREAD: 'DELETE_THREAD',
    NO_MORE_THREADS: 'NO_MORE_THREADS',
    LOAD_THREADS_SUCCESS: 'LOAD_THREADS_SUCCESS',
    LOAD_THREAD_SUCCESS: 'LOAD_THREAD_SUCCESS',
    ENTER_THREAD_VIEW: 'ENTER_THREAD_VIEW',
    EXIT_THREAD_VIEW: 'EXIT_THREAD_VIEW',
    ENTER_THREAD_LIST: 'ENTER_THREAD_LIST',
    EXIT_THREAD_LIST: 'EXIT_THREAD_LIST',
    EXIT_POST_VIEW: 'EXIT_POST_VIEW',
    LOAD_POSTS_SUCCESS: 'LOAD_POSTS_SUCCESS'
};
