export const messageConstants = {
    ADD_MESSAGE_POST: 'ADD_MESSAGE_POST',
    ADD_MESSAGE: 'ADD_MESSAGE',
    RECIEVE_MESSAGE_POST: 'RECIEVE_MESSAGE_POST',
    LOAD_MESSAGES_SUCCESS: 'LOAD_MESSAGES_SUCCESS',
    LOAD_MESSAGE_SUCCESS: 'LOAD_MESSAGE_SUCCESS',
    LOAD_MESSAGE_POSTS_SUCCESS: 'LOAD_MESSAGE_POSTS_SUCCESS',
    UPDATE_MESSAGE_USERS: 'UPDATE_MESSAGE_USERS',
    CLEAR_MESSAGE_USERS: 'CLEAR_MESSAGE_USERS'
};
